COPYANIM_NAME_CONST = "Copy Anim"
COPYANIM_DESC_CONST = "Copy or transfer animations between controls."
COPYANIM_WIDTH_CONST = 250
COPYANIM_HEIGHT_CONST = 400
COPYANIM_ICON_CONST = COPYANIM_NAME_CONST

BOOKMARK_NAME_CONST = "Bookmark Tools"
BOOKMARK_DESC_CONST = "Edit and offset bookmarks more efficiently"
BOOKMARK_WIDTH_CONST = 250
BOOKMARK_HEIGHT_CONST = 250
BOOKMARK_ICON_CONST = BOOKMARK_NAME_CONST
